package com.amit.demo.StudentServer.Service;

import com.amit.demo.StudentServer.DTO.CreateStudentRequestDTO;
import com.amit.demo.StudentServer.DTO.CreateStudentResponseDTO;
import com.amit.demo.StudentServer.Entity.Student;
import com.amit.demo.StudentServer.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    private final StudentRepository studentRepository;

    @Autowired
    public StudentService(StudentRepository studentRepository) {
        this.studentRepository = studentRepository;
    }

    public CreateStudentResponseDTO createStudent(CreateStudentRequestDTO requestDTO) {
        if (requestDTO == null) return null;

        Student student = new Student();
        student.setName(requestDTO.getName() != null ? requestDTO.getName().trim() : null);
        student.setAge(requestDTO.getAge());
        student.setDepartment(requestDTO.getDepartment() != null ? requestDTO.getDepartment().trim() : null);

        // Timestamps are automatically generated by @PrePersist in the Student entity
        return mapToResponseDTO(studentRepository.save(student));
    }

    public CreateStudentResponseDTO getStudentById(int id) {
        return studentRepository.findById(id)
                .map(this::mapToResponseDTO)
                .orElse(null);
    }

    public CreateStudentResponseDTO putStudent(int id, CreateStudentRequestDTO requestDTO) {
        if (requestDTO == null) return null;

        return studentRepository.findById(id).map(existingStudent -> {
            existingStudent.setName(requestDTO.getName() != null ? requestDTO.getName().trim() : null);
            existingStudent.setAge(requestDTO.getAge());
            existingStudent.setDepartment(requestDTO.getDepartment() != null ? requestDTO.getDepartment().trim() : null);

            // @PreUpdate in the Student entity handles the updated timestamp automatically
            return mapToResponseDTO(studentRepository.save(existingStudent));
        }).orElse(null);
    }

    public CreateStudentResponseDTO patchStudent(int id, CreateStudentRequestDTO requestDTO) {
        if (requestDTO == null) return null;

        return studentRepository.findById(id).map(existingStudent -> {
            if (requestDTO.getName() != null && !requestDTO.getName().trim().isEmpty()) {
                existingStudent.setName(requestDTO.getName().trim());
            }
            if (requestDTO.getDepartment() != null && !requestDTO.getDepartment().trim().isEmpty()) {
                existingStudent.setDepartment(requestDTO.getDepartment().trim());
            }
            if (requestDTO.getAge() > 0) {
                existingStudent.setAge(requestDTO.getAge());
            }
            return mapToResponseDTO(studentRepository.save(existingStudent));
        }).orElse(null);
    }

    public boolean deleteStudent(int id) {
        if (!studentRepository.existsById(id)) {
            return false;
        }
        studentRepository.deleteById(id);
        return true;
    }

    private CreateStudentResponseDTO mapToResponseDTO(Student student) {
        CreateStudentResponseDTO responseDTO = new CreateStudentResponseDTO();
        responseDTO.setId(student.getId());
        responseDTO.setName(student.getName());
        responseDTO.setAge(student.getAge());
        responseDTO.setDepartment(student.getDepartment());
        return responseDTO;
    }
}
